name: HarryPotterSpells
main: com.lavacraftserver.HarryPotterSpells.HarryPotterSpells
authors: [Kezz101, np98765]
version: 1.0
softdepend: [Vault]
commands:
  teach:
    description: Teach a player a spell
    permission: HarryPotterSpells.commands.teach
permissions:
  HarryPotterSpells.use:
    description: Use the wand
    default: op
  HarryPotterSpells.commands.teach:
    description: Access to /teach
    default: op