# Only enable if you want to enable debugging mode
DebugMode: false

VaultEnabled: true
  # Vault is required for spell signs and sorting
  
sorting:
    enabled: true
    permission-node: true
      # Whether the user will gain house.housename when sorted
    permission-group: false
      # Whether the user will be sorted into a permissions group

shout-on-spell-use: false
notify-on-spell-use: true

## Unimplemented in the code ##
spell-castable-with-command: true
spell-castable-with-chat: true
disable-stick-crafting: true



##########################################
## Ability to define custom spell names ##
##########################################
