##################
# General Config #
##################

# Only enable if you want to enable debugging mode
DebugMode: false

VaultEnabled: true
  # Vault is required for spell signs and sorting
WorldGuardEnabled: true
  # WorldGuard is required for build checks on block editing spells
LogBlockEnabled: true
  # LogBlock is required for spell logging
  
SortingHat:
    enabled: true
    addHousePermissionNodes: true
      # Whether the user will gain house.housename when sorted
    addHouseGroups: false
      # Whether the user will be sorted into a permissions group

SpellSigns:
    textForLine1: SpellShop!
      # The text that should be on Line 1 of a SpellSign

shout-on-spell-use: false
notify-on-spell-use: true
spell-castable-with-command: true
spell-particle-toggle: true

## Unimplemented in the code ##
spell-castable-with-chat: true
disable-stick-crafting: true



#########################
## Spell Configuration ##
#########################

Multicorfors:
  explosionEffect: true
