##################
# General Config #
##################

# Only enable if you want to enable debugging mode
DebugMode: false
      
WandGive:  # The command that 'summons' a wand with a command
  explosionEffect: false

wand-id: 280  # Will default to 280 (stick)
shout-on-spell-use: false  # If the player should say 'Spellname!' on every spell cast
notify-on-spell-use: true  # If we should notify the player when they cast a spell
spell-particle-toggle: false  # The purple particle effect that happens when the spell is cast (Kezz thinks it's ugly)
disable-wand-crafting: true  # Fairly obvious... Should we disable wand crafting?
disable-all-crafting: false  # Should we disable all crafting?
spell-castable-with-chat: true  # If a spell is castable on the chatting of 'Spellname!'

#########################
## Spell Configuration ##
#########################

## When configuring durations, ticks (1/20 of a second) are assumed. If you'd like to specify ticks, append a 't' to the value.
## For example, 600t = 600 ticks = 30 seconds
## while 600 (without the t) = 600 seconds
spells:
  accio:
    radius: 3  # The maximum distance drops can be from the player to still be attracted
  avis:
    chickens: 5  # How many chickens the wand should shoot
  confundo:
    duration: 200t  # How long the target should be confused for
  deprimo:
    duration: 100t  # How long the target should be slowed for
  episkey:
    duration: 200t  # How long the target should be healed for
  evanesco:
    duration: 300  # How many TICKS the caster will be invisible for
  incendio:
    duration: 100t  # How long the fire should last
  multicorfors:
    explosionEffect: true  # Should an explosion happen on color change
  obscuro:
    duration: 600t  # How long the target should be blinded for
  petrificustotalus:
    duration: 600  # How many TICKS the target should be petrified (frozen) for
  spongify:
    duration: 600  # How many TICKS damage should be cancelled for
  stupefy:
    knockback: 5  # How much the target should be knocked backwards
    confusion-duration: 200t  # How long the target should be confused for
    weakness-duration: 100t  # How long the target should be weakened for
  timespell:
    lightning: true  # Should lightning strike on casting of the spell
  wingardiumleviosa:
    cancelfalldamage: true  # Should fall damage be cancelled when flying with the spell
    duration: 200t  # How long the caster should be able to fly for
