############################
## General Configuration  ##
## http://tiny.cc/hpsconf ##
############################

# Only enable if you want to enable debugging mode
debug-mode: false
      
wand-give:  # The command that 'summons' a wand with a command
  explosion-effect: false

wand-id: 280  # Will default to 280 (stick)
shout-on-spell-use: false  # If the player should say 'Spellname!' on every spell cast
notify-on-spell-use: true  # If we should notify the player when they cast a spell
spell-particle-toggle: false  # The purple particle effect that happens when the spell is cast (Kezz thinks it's ugly)
disable-wand-crafting: true  # Fairly obvious... Should we disable wand crafting?
disable-all-crafting: false  # Should we disable all crafting?
spell-castable-with-chat: true  # If a spell is castable on the chatting of 'Spellname!'

#########################
## Spell Configuration ##
#########################

## When configuring spells, seconds are assumed. If you'd like to specify ticks (1/20 of a second), append a 't' to the value.
## For example, 600t = 600 ticks = 30 seconds
## while 600 (without the t) = 600 seconds
spells:
  accio:
    radius: 5  # The maximum distance drops can be from the player to still be attracted
  avis:
    chickens: 5  # How many chickens the wand should shoot
  confundo:
    duration: 200t  # How long the target should be confused for
  deprimo:
    duration: 100t  # How long the target should be slowed for
  episkey:
    duration: 100t  # How long the target should be healed for
  evanesco:
    duration: 300  # How many TICKS the caster will be invisible for
  expelliarmus:
    disarm-weapons: true  # Should Expelliarmus disarm weapons (swords and bows) as well as wands? 
  homenum-revelio:
    box:  # The size of the box used in the search for nearby players
      x: 10  # 1/2 the size of the box along x axis
      y: 10  # 1/2 the size of the box along y axis
      z: 10  # 1/2 the size of the box along z axis
    effect-color: yellow  # The color the effect around the hidden player should be
  incendio:
    duration: 100t  # How long the fire should last
  multicorfors:
    explosion-effect: true  # Should an explosion happen on color change
  obscuro:
    duration: 400t  # How long the target should be blinded for
  petrificus-totalus:
    duration: 100  # How many TICKS the target should be petrified (frozen) for
  spongify:
    duration: 600  # How many TICKS fall damage should be cancelled for
  stupefy:
    vertical-knockback: 2  # How much the target should be knocked backwards
    horizontal-knockback: 0.5  # How much the target should be knocked upwards (into the air)
    confusion-duration: 200t  # How long the target should be confused for
    weakness-duration: 100t  # How long the target should be weakened for
    damage: 2  # How many half-hearts the user should be damaged (set to 0 for no damage)
  timespell:
    lightning: true  # Should lightning strike on casting of the spell
  wingardium-leviosa:
    cancel-fall-damage: true  # Should fall damage be cancelled when flying
    duration: 200  # How many TICKS the caster should be able to fly for
    
cooldowns:
## Do not use 0 for no cooldown. Use -1 instead.
## All cooldown values are in seconds. DO NOT USE 't'.
## Give the permission node 'HarryPotterSpells.nocooldown to bypass cooldowns.

  accio: 5
  aguamenti: 90
  'alarte ascendare': 45
  'avada kedavra': 300
  avis: 300
  confringo: 45 
  confundo: 180
  crucio: 300
  deprimo: 180
  enderchest: -1
  episkey: 60
  evanesco: 45
  expelliarmus: 120
  'finite incantatem': 45 
  glacius: 120
  'homenum revelio': 600
  incendio: 45
  'magna tonitrus': 60
  morsmordre: 60
  multicorfors: 30
  obscuro: 90
  orchideous: 45 
  'petrificus totalus': 300
  reducto: 300
  reparo: 14400
  sectumsempra: 300
  sonorus: 15
  spongify: 60
  stupefy: 120
  time: 600
  tree: 105
  'windgardium leviosa': 180
