##################
# General Config #
##################

# Only enable if you want to enable debugging mode
DebugMode: false
      
WandGive: # The command that 'summons' a wand with a command
  explosionEffect: false

wand-id: 280 # Will default to 280 (stick)
shout-on-spell-use: false # If the player should say 'Spellname!' on every spell cast
notify-on-spell-use: true # If we should notify the player when they cast a spell
spell-particle-toggle: false # The purple particle effect that happens when the spell is cast (Kezz thinks it's ugly)
disable-wand-crafting: true # Fairly obvious... Should we disable wand crafting?
disable-all-crafting: false # Should we disable all crafting?
spell-castable-with-chat: true # If a spell is castable on the chatting of 'Spellname!'

#########################
## Spell Configuration ##
#########################

spells:
  avis:
    chickens: 5 # How many chickens the wand should shoot
  incendio:
    duration: 100 # How long the fire should last in ticks (1/20 of a second)
  multicorfors:
    explosionEffect: true # Should an explosion happen on colour change?
  time:
    lightning: true # Should lightning strike on casting of the spell