name: HarryPotterSpells
main: com.lavacraftserver.HarryPotterSpells.HarryPotterSpells
authors: [np98765, Kezz101]
version: 1.0
softdepend: [Vault]
commands:
  teach:
    description: Teach a player a spell.
    permission: HarryPotterSpells.commands.teach
  unteach:
    description: Specified player loses ability to cast specified spell.
    permission: HarryPotterSpells.commands.unteach
  sort:
    description: Specified player is assigned a house.
    permission: HarryPotterSpells.commands.sort
permissions:
  HarryPotterSpells.use:
    description: Use the wand
    default: op
  HarryPotterSpells.commands.teach:
    description: Access to /teach
    default: op
  HarryPotterSpells.sign.buy:
    description: Allows users to buy from spell signs
    default: op
  HarryPotterSpells.sign.create:
    description: Allows user to create a spell sign
    default: op