name: HarryPotterSpells
main: com.lavacraftserver.HarryPotterSpells.HarryPotterSpells
authors: [np98765, Kezz101]
version: ALPHA 0.1
softdepend: [Vault]
commands:
  teach:
    description: Teach a player a spell
    permission: HarryPotterSpells.commands.teach
permissions:
  HarryPotterSpells.use:
    description: Use the wand
    default: op
  HarryPotterSpells.commands.teach:
    description: Access to /teach
    default: op
  HarryPotterSpells.sign.buy:
    description: Allows users to buy from spell signs
    default: op
  HarryPotterSpells.sign.create:
    description: Allows user to create a spell sign
    default: op